site_name: nmsd
extra:
  homepage: https://nmsd.xyz

theme:
  icon:
    logo: bootstrap/shield
  favicon: favicon.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
  name: material
  palette:
    primary: black
    accent: blue
  custom_dir: overrides

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true


# Footer
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/nimasaed/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/nimasaed
    - icon: fontawesome/brands/github
      link: https://github.com/nimasaed
  generator: false

copyright: Copyright &copy; 2019 - 2022 Nima Saed

# pages
nav:
  - 'About': 'index.md'
  - 'Blog':
    - '2021':
      - 'AWS Profile Changer': 'blog/AWS-Profile-changer.md'
    - '2019':
      - 'MSF on Docker': 'blog/Metasploit-Framework-console.md'
  - 'Notes':
    - 'Languages':
      - 'Bash Tips': 'notes/bash-tips.md'
